[정렬, 맵, 셋] 8월 19일
Altu-Bitu-7/Altu-Bitu-KimYeJi pull request #1
Opened 2024-08-19 10:11 UTC by xyzwv

## 인적사항
학번: 2176082 <br>
이름: 김예지 <br><br>

## 과제제출
기존제출: 1431, 14425, 19636, 1946, 9375 <br>
추가제출:  <br>

2024-08-25 13:32 UTC, chae-jpg requested changes
[정렬, 맵, 셋 구현 코드리뷰 완료]
14425(P1) 
예지님 안녕하세요! 코드 리뷰 완료되었습니다👍 
도전문제까지 모두 풀어주시다니 정말 멋져요! 수고 많으셨습니다👍
과제 제출로는 인정되었지만, 과제의 의도와 다르게 푸신 문제가 있어서 간단한 코멘트 남겼습니다!
확인하시고 따라서 수정하시면 정말 좋을 것 같아요 💯  
궁금하신 점이 있다면 언제나 리뷰어를 호출해주세요😊

2024-08-25 13:32 UTC, chae-jpg commented on 01_정렬_맵_셋/14425.cpp
> +        if(binary_search(v.begin(), v.end(), s)) count++;
P1
맞아요, 이분탐색을 통해서도 빠르게 탐색을 수행할 수 있죠! 
하지만 이번 시간에 배운 빠르고 효율적이게 자료를 저장하고 탐색할 수 있는 자료구조가 있었어요! 그 자료구조를 이용해서 문제를 풀어보면 더 좋을 것 같아요 👍

2024-08-25 15:54 UTC, flowing1ife reviewed
[정렬, 맵, 셋 구현 코드리뷰 완료]
1431(P2) 
코드 리뷰 완료하였습니다 !
전체적으로 주석을 추가해서 코드의 가독성을 높이면 더욱 좋을 것 같습니다 ㅎㅎ
도전문제까지 너무 수고 많으셨습니다 :)

2024-08-25 15:54 UTC, flowing1ife commented on 01_정렬_맵_셋/1431.cpp
> +    }
P2
sum1 과 sum2가 같은 행위를 반복하고 있어요 ! 따라서 따로 함수화하는 것을 권장드립니다 !
위처럼 시리얼 번호를 구성하는 숫자의 합을 구하는 역할을 하는 코드는 cmp 함수가 아닌 sumNum과 같은 함수로 빼면 좋을 것 같아요 ㅎㅎ

2024-08-27 09:22 UTC, xyzwv commented
@chae-jpg 14425번 수정하였습니다!

2024-08-28 07:05 UTC, chae-jpg approved these changes
14425번 수정 확인했습니다! 머지하셔도 좋습니다ㅎㅎ

2024-08-28 13:08 UTC, merged